export enum CategoryEnum {
  FEEDING = 'FEEDING',
  HEALTH = 'HEALTH',
  HOME = 'HOME',
  TRANSPORT = 'TRANSPORT',
  EDUCATION = 'EDUCATION',
  LEISURE = 'LEISURE',
  UNFORESEEN = 'UNFORESEEN',
  OTHERS = 'OTHERS'
}
